// Componente compartilhado: use <footer class="site-footer" data-site-footer></footer>
// e inclua este arquivo em qualquer nova página para manter o rodapé idêntico.
const siteLinks={"Início e ofertas":"index.html","Sobre o Economizaí":"sobre.html","Como encontramos as ofertas":"como-encontramos-ofertas.html","Transparência":"transparencia.html","Política de Privacidade":"privacidade.html","Termos de Uso":"termos.html","Política de Cookies":"cookies.html","Contato":"contato.html"};
const socialLinks={YouTube:"https://www.youtube.com/@reiwo",Instagram:"https://www.instagram.com/reiwooficial/",Twitch:"https://www.twitch.tv/reiwooficial",TikTok:"https://www.tiktok.com/@reiwooficial_"};
function renderSiteLinks(items){return Object.entries(items).map(([label,url])=>`<a href="${url}" ${url.startsWith('http')?'target="_blank" rel="noopener"':''}>${label}</a>`).join('');}
const sharedFooter=document.querySelector('[data-site-footer]');
if(sharedFooter){sharedFooter.innerHTML=`<div class="footer-grid"><div><div class="footer-brand">ECONOMIZAÍ<small>Um projeto ReiWO.</small></div></div><div class="footer-col"><h2>NAVEGAÇÃO</h2>${renderSiteLinks({'Início e ofertas':'index.html','Sobre o Economizaí':'sobre.html',Contato:'contato.html'})}</div><div class="footer-col"><h2>INSTITUCIONAL</h2>${renderSiteLinks({'Como encontramos as ofertas':'como-encontramos-ofertas.html',Transparência:'transparencia.html','Política de Privacidade':'privacidade.html','Termos de Uso':'termos.html','Política de Cookies':'cookies.html'})}</div><div class="footer-col"><h2>REIWO</h2>${renderSiteLinks(socialLinks)}</div></div><p class="affiliate-note">O Economizaí pode receber comissão por meio de determinados links de afiliados. Isso não gera custo adicional para você. Preços e condições podem ser alterados pelas lojas sem aviso prévio.</p><p class="copyright">© 2026 Economizaí. Todos os direitos reservados.</p>`;}
const sharedHeader=document.querySelector('[data-site-header]');
if(sharedHeader){sharedHeader.innerHTML=`<div class="ticker">ECONOMIZE MAIS • COMPRE MELHOR • AS MELHORES OFERTAS, SEMPRE!</div><nav class="top-nav"><a class="brand" href="index.html">ECONOMIZAÍ</a><a class="nav-link" href="index.html">Ofertas</a><a class="nav-link" href="contato.html">Contato</a><button class="nav-btn" onclick="toggleMenu()">☰ Categorias</button></nav><aside class="drawer" id="siteMenu"><button class="drawer-close" onclick="toggleMenu()" aria-label="Fechar">×</button><h2>Explorar</h2><h3>Categorias</h3><a href="index.html">Consoles</a><a href="index.html">Eletrodomésticos</a><a href="index.html">Games</a><a href="index.html">Hardware</a><a href="index.html">Informática</a><a href="index.html">Periféricos</a><a href="index.html">Smartphones</a><a href="index.html">TVs e Áudio</a><h3>Links</h3>${renderSiteLinks({Contato:'contato.html',...socialLinks})}</aside>`;}
