const content=document.getElementById('content');let currentView='reports';
const labels={price_changed:'Preço mudou',unavailable:'Produto indisponível',broken_link:'Link não funciona',other:'Outro problema'};
const states={reports:{new:'Novo',reviewing:'Em análise',resolved:'Resolvido',archived:'Arquivado'},contacts:{new:'Nova',refused:'Recusada',answered:'Respondida',archived:'Arquivada'}};
const escapeHtml=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function offer(report){return Array.isArray(report.offers)?report.offers[0]:report.offers}function productTitle(report){const product=Array.isArray(offer(report)?.products)?offer(report).products[0]:offer(report)?.products;return product?.title||'Produto removido ou não encontrado'}function productId(report){return offer(report)?.external_product_id||''}
function options(view,status){return Object.entries(states[view]).map(([value,label])=>`<option value="${value}"${value===status?' selected':''}>${label}</option>`).join('')}
async function load(){const route=currentView==='reports'?'/api/admin/reportes':'/api/admin/contatos';const response=await fetch(route,{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();return currentView==='reports'?data.reports||[]:data.contacts||[]}
async function update(id,status){const route=currentView==='reports'?`/api/admin/reportes/${encodeURIComponent(id)}`:`/api/admin/contatos/${encodeURIComponent(id)}`;return fetch(route,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})})}
function actionPanel(view,item,open=''){return `<div class="status"><select aria-label="Status">${options(view,item.status)}</select><button class="confirm" type="button" disabled>Confirmar alteração</button><button class="history" type="button">Ver histórico</button>${open}</div><div class="audit" hidden></div>`}
function makeReport(report){const card=document.createElement('article');card.className=`record status-${report.status}`;const id=productId(report),date=new Date(report.created_at).toLocaleString('pt-BR');card.innerHTML=`<div><span class="tag">${labels[report.report_type]||'Reporte'}</span><h2>${escapeHtml(productTitle(report))}</h2><p>${report.message?escapeHtml(report.message):'O usuário não deixou uma observação adicional.'}</p><div class="meta">Enviado em ${date}</div></div>${actionPanel('reports',report,id?`<a class="open" href="produto-dinamico.html?id=${encodeURIComponent(id)}">Abrir oferta</a>`:'')}`;bindStatus(card,report,'reports');return card}
function makeContact(contact){const card=document.createElement('article');card.className=`record status-${contact.status}`;const date=new Date(contact.created_at).toLocaleString('pt-BR');const phone=contact.phone?` · ${escapeHtml(contact.phone)}`:'';card.innerHTML=`<div><span class="tag">Contato</span><h2>${escapeHtml(contact.subject)}</h2><p class="contact-line">${escapeHtml(contact.name)} · ${escapeHtml(contact.email)}${phone}</p><p>${escapeHtml(contact.message)}</p><div class="meta">Enviado em ${date}</div></div>${actionPanel('contacts',contact)}`;bindStatus(card,contact,'contacts');return card}
function bindStatus(card,item,view){const select=card.querySelector('select'),confirm=card.querySelector('.confirm'),history=card.querySelector('.history'),audit=card.querySelector('.audit');const loadHistory=async()=>{audit.hidden=false;audit.textContent='Carregando histórico…';history.textContent='Ocultar histórico';const type=view==='reports'?'report':'contact';try{const response=await fetch(`/api/admin/auditoria?tipo=${type}&id=${encodeURIComponent(item.id)}`);const {logs=[]}=await response.json();audit.innerHTML=logs.length?logs.map(log=>`<div>${new Date(log.created_at).toLocaleString('pt-BR')} — <strong>${escapeHtml(states[view][log.previous_status]||log.previous_status)}</strong> → <strong>${escapeHtml(states[view][log.next_status]||log.next_status)}</strong> por ${escapeHtml(log.actor_name||'Administrador')}</div>`).join(''):'Nenhuma alteração registrada ainda.'}catch{audit.textContent='Não foi possível carregar o histórico.'}};select.addEventListener('change',()=>{confirm.disabled=select.value===item.status});confirm.addEventListener('click',async()=>{confirm.disabled=true;confirm.textContent='Salvando…';const response=await update(item.id,select.value);if(!response.ok){select.value=item.status;confirm.textContent='Confirmar alteração';window.EconomizaiUI?.toast('Não foi possível atualizar este item.','error');return}card.classList.remove(`status-${item.status}`);item.status=select.value;card.classList.add(`status-${item.status}`);confirm.textContent='Alteração salva';if(!audit.hidden)loadHistory();window.setTimeout(()=>{confirm.textContent='Confirmar alteração';confirm.disabled=true},1400)});history.addEventListener('click',()=>{if(!audit.hidden){audit.hidden=true;history.textContent='Ver histórico'}else loadHistory()})}
async function render(){try{const items=await load();if(!items.length){content.className='empty';content.textContent=currentView==='reports'?'Nenhum reporte recebido até agora.':'Nenhuma mensagem de contato recebida até agora.';return}content.className='list';content.replaceChildren(...items.map(item=>currentView==='reports'?makeReport(item):makeContact(item)))}catch{content.className='empty';content.textContent='Não foi possível carregar esta área agora.'}}
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>{currentView=button.dataset.view;document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab===button));render()}));render();
