-- Economizaí · Monitoramento de preço V3 seguro
-- Execute uma vez no SQL Editor do projeto Supabase do Economizaí.

alter table public.offers
  add column if not exists last_check_status text,
  add column if not exists last_check_error text,
  add column if not exists consecutive_check_failures integer not null default 0;

create table if not exists public.offer_monitoring_logs (
  id bigint generated by default as identity primary key,
  offer_id uuid not null references public.offers(id) on delete cascade,
  checked_at timestamptz not null default now(),
  outcome text not null,
  product_title text,
  page_title text,
  public_url text,
  stored_current_price numeric,
  detected_current_price numeric,
  detected_original_price numeric,
  price_source text,
  parser_version text not null default 'n8n-v3-seguro',
  reason text,
  http_status integer
);

create index if not exists offer_monitoring_logs_offer_checked_idx
  on public.offer_monitoring_logs (offer_id, checked_at desc);

create index if not exists offer_monitoring_logs_outcome_checked_idx
  on public.offer_monitoring_logs (outcome, checked_at desc);
